/**
 * Sample historical and operational wells in Northeast India
 * (Upper Assam Basin & Foothills — OIL & ONGC operations)
 */
export const NORTHEAST_SAMPLE_WELLS = [
  {
    well_id: "W-104",
    name: "Naharkatiya-104 (W-104)",
    field: "Naharkatiya",
    basin: "Upper Assam Shelf",
    district: "Dibrugarh, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.2892,
    longitude: 95.3421,
    total_depth_m: 3850,
    formation: "Barail Sandstone",
    status: "Active / Monitored",
    events_count: 4,
    notes: "Primary offset intelligence candidate with historical mud-loss records",
  },
  {
    well_id: "W-105",
    name: "Naharkatiya-105 (Offset)",
    field: "Naharkatiya",
    basin: "Upper Assam Shelf",
    district: "Dibrugarh, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.2985,
    longitude: 95.3564,
    total_depth_m: 3920,
    formation: "Tipam Sandstone",
    status: "Offset Monitor",
    events_count: 2,
    notes: "Offset well with tight hole and differential sticking history",
  },
  {
    well_id: "W-106",
    name: "Duliajan Deep-106",
    field: "Duliajan",
    basin: "Upper Assam Shelf",
    district: "Dibrugarh, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.3541,
    longitude: 95.3188,
    total_depth_m: 4100,
    formation: "Kopili Formation",
    status: "Active Producer",
    events_count: 3,
    notes: "Deep development well with high torque across Kopili shales",
  },
  {
    well_id: "DIG-089",
    name: "Digboi Discovery-89",
    field: "Digboi",
    basin: "Assam-Arakan Fold Belt",
    district: "Tinsukia, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.3884,
    longitude: 95.6291,
    total_depth_m: 2450,
    formation: "Tipam Sandstone",
    status: "Historic Producer",
    events_count: 1,
    notes: "Shallow historical well with mature reservoir pressures",
  },
  {
    well_id: "DIG-112",
    name: "Digboi North-112",
    field: "Digboi",
    basin: "Assam-Arakan Fold Belt",
    district: "Tinsukia, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.4012,
    longitude: 95.6425,
    total_depth_m: 2780,
    formation: "Surma Group",
    status: "Active",
    events_count: 5,
    notes: "Faulted structure with fractured shale and borehole sloughing",
  },
  {
    well_id: "MOR-045",
    name: "Moran Main-45",
    field: "Moran",
    basin: "Upper Assam Shelf",
    district: "Dibrugarh, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.1824,
    longitude: 94.9312,
    total_depth_m: 3740,
    formation: "Barail Main Sand",
    status: "Active Producer",
    events_count: 3,
    notes: "High pressure Barail section with seepage losses at casing shoe",
  },
  {
    well_id: "MOR-062",
    name: "Moran South-62",
    field: "Moran",
    basin: "Upper Assam Shelf",
    district: "Sivasagar, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.1510,
    longitude: 94.9085,
    total_depth_m: 3890,
    formation: "Barail Coal-Shale",
    status: "Active",
    events_count: 2,
    notes: "Interbedded coal beds and shale requiring managed ECD",
  },
  {
    well_id: "BAGH-007",
    name: "Baghjan Deep-07",
    field: "Baghjan",
    basin: "Upper Assam Shelf",
    district: "Tinsukia, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.6045,
    longitude: 95.4128,
    total_depth_m: 4250,
    formation: "Barail Sandstone",
    status: "Monitored Gas/Oil",
    events_count: 6,
    notes: "High-pressure gas cap well with strict kick detection protocols",
  },
  {
    well_id: "HAP-024",
    name: "Hapjan-24",
    field: "Hapjan",
    basin: "Upper Assam Shelf",
    district: "Tinsukia, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.4312,
    longitude: 95.2284,
    total_depth_m: 3620,
    formation: "Girujan Clay / Tipam",
    status: "Active",
    events_count: 1,
    notes: "Stable borehole conditions with minor washouts in claystone",
  },
  {
    well_id: "TEN-008",
    name: "Tengakhat-08",
    field: "Tengakhat",
    basin: "Upper Assam Shelf",
    district: "Dibrugarh, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.3620,
    longitude: 95.1850,
    total_depth_m: 3710,
    formation: "Tipam Sandstone",
    status: "Active Producer",
    events_count: 2,
    notes: "Normal pressure regime with good drilling efficiency",
  },
  {
    well_id: "KUM-003",
    name: "Kumchai-03 (Arunachal)",
    field: "Kumchai",
    basin: "Arunachal Foothills",
    district: "Changlang, Arunachal Pradesh",
    operator: "Oil India Limited (OIL)",
    latitude: 27.3245,
    longitude: 96.0289,
    total_depth_m: 4400,
    formation: "Girujan / Tipam",
    status: "Active Foothills",
    events_count: 4,
    notes: "Tectonically stressed foothills environment with hole packoff risks",
  },
  {
    well_id: "BOR-019",
    name: "Borholla-19",
    field: "Borholla",
    basin: "South Assam Shelf",
    district: "Jorhat, Assam",
    operator: "ONGC / OIL Basin",
    latitude: 26.4715,
    longitude: 93.9240,
    total_depth_m: 3210,
    formation: "Sylhet Limestone",
    status: "Active Producer",
    events_count: 2,
    notes: "Carbonate reservoir section with severe lost circulation zones",
  },
  {
    well_id: "LAK-078",
    name: "Lakwa-78",
    field: "Lakwa",
    basin: "Upper Assam Shelf",
    district: "Charaideo, Assam",
    operator: "Assam Shelf Operations",
    latitude: 27.0241,
    longitude: 94.8825,
    total_depth_m: 3550,
    formation: "Barail Sandstone",
    status: "Active Producer",
    events_count: 3,
    notes: "Multi-layered pay zone with depleted pressure intervals",
  },
  {
    well_id: "GEL-032",
    name: "Geleki-32",
    field: "Geleki",
    basin: "Upper Assam Shelf",
    district: "Sivasagar, Assam",
    operator: "Assam Shelf Operations",
    latitude: 26.8512,
    longitude: 94.7562,
    total_depth_m: 4120,
    formation: "Tipam Sandstone",
    status: "Active Producer",
    events_count: 4,
    notes: "Deep high-temperature well with thermal mud rheology challenges",
  },
  {
    well_id: "RUD-015",
    name: "Rudrasagar-15",
    field: "Rudrasagar",
    basin: "Upper Assam Shelf",
    district: "Sivasagar, Assam",
    operator: "Assam Shelf Operations",
    latitude: 26.9890,
    longitude: 94.6321,
    total_depth_m: 3380,
    formation: "Barail Main Sand",
    status: "Active",
    events_count: 1,
    notes: "Classic structural trap with high quality sandstone reservoir",
  },
  {
    well_id: "KUS-011",
    name: "Kusijan-11",
    field: "Kusijan",
    basin: "Upper Assam Shelf",
    district: "Tinsukia, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 27.5120,
    longitude: 95.4215,
    total_depth_m: 3790,
    formation: "Barail Sandstone",
    status: "Active",
    events_count: 2,
    notes: "Northern flank development well with intermittent gas influx",
  },
  {
    well_id: "JRH-005",
    name: "Jorhat Deep-05",
    field: "Jorhat",
    basin: "Upper Assam Shelf",
    district: "Jorhat, Assam",
    operator: "Oil India Limited (OIL)",
    latitude: 26.7580,
    longitude: 94.2150,
    total_depth_m: 4350,
    formation: "Basement / Kopili",
    status: "Exploration Well",
    events_count: 3,
    notes: "Granitic basement exploration with high abrasive bit wear",
  },
];

export const NORTHEAST_UNMAPPED_SAMPLE = [
  {
    well_id: "DUL-EXP-01",
    name: "Duliajan Exploration 01",
    field: "Duliajan",
    formation: "Tipam Sandstone",
    reason: "Legacy coordinates in archive format",
  },
  {
    well_id: "BOR-OLD-04",
    name: "Borholla Historical 04",
    field: "Borholla",
    formation: "Kopili Formation",
    reason: "Borehole deviation survey under digitization",
  },
];
